function shapemat = mk_shape(varargin)
%MK_SHAPE Converts a matrix using a step function.
%
%   SHAPEMAT = MK_SHAPE(PIXELMAP, RADIUS [,PXPITCH]) returns a matrix with the
%   same size as PIXELMAP. Values in the PIXELMAP are thresholded at the value
%   of RADIUS, and values within the range of PXPITCH from the threshold will be
%   anti-aliased.
%
%   Arguments:
%      PIXELMAP - an image matrix, usually generated by MAP_* functions.
%      RADIUS   - a threshold value.
%      PXPITCH  - an anti-aliasing range, 1 if empty or not provided.
%
%   Example:
%      <a href="matlab:imshow(mk_shape(map_radial(200), 50));">imshow(mk_shape(map_radial(200), 50));</a>
%
%   See also MAP_SYMMETRIC, MAP_RADIAL, MAP_RECTANGULAR.

	pixelmap = pretina_arg(varargin, 1, mfilename, 'pixelmap', [], {'numeric'}, {'nonempty', 'real', 'finite', 'nonnan'});
	radius   = pretina_arg(varargin, 2, mfilename, 'radius',   [], {'numeric'}, {'scalar', 'real', 'finite', 'nonnan'});
	pxpitch  = pretina_arg(varargin, 3, mfilename, 'pxpitch',  1,  {'numeric'}, {'scalar', 'real', 'finite', 'nonnan', 'positive'});

	shapemat = max(min((radius - pixelmap) * pxpitch + .5, pxpitch), 0) / pxpitch;
end